Repository minvws/nl-rdo-manon, pull requests merged in 2025-09, with the labels that each got.

#972 fix: Base styling
  docs/src/lib/DefaultFooter.svelte
  docs/src/routes/components/components/button-secondary/+page.svelte
  docs/src/routes/components/components/button/+page.md
  docs/src/routes/components/components/button/button-secondary/+page.svelte
  docs/src/scss/main.scss
  manon/components/article-section.scss
  manon/components/article.scss
  manon/components/footer.scss
  manon/components/heading.scss
  manon/components/headings.scss
  manon/components/logo.scss
  manon/components/section.scss
  manon/omgezet/footer-navigation-link-active.scss
  manon/omgezet/footer-navigation-link-focus.scss
  manon/omgezet/footer-navigation-link-hover.scss
  manon/omgezet/footer-navigation-link-variables.scss
  manon/omgezet/footer-navigation-link-visited.scss
  manon/omgezet/footer-navigation-link.scss
  manon/omgezet/notification-confirmation-page.scss
  manon/omgezet/notification-error-page.scss
  manon/omgezet/notification-explanation-page.scss
  manon/omgezet/notification-form.scss
  manon/omgezet/notification-paragraph.scss
  manon/omgezet/notification-system-message.scss
  manon/omgezet/notification-system-page.scss
  manon/omgezet/notification-table.scss
  manon/omgezet/notification-warning-page.scss
  manon/variables/_footer.scss
  manon/variables/_logo.scss
  themes/icore-open/_index.scss
  themes/kat/_index.scss
Labels: v18

#1021 fix: layout fixes
  docs/src/img/logo-dark.svg
  docs/src/routes/components/+page.svelte
  docs/src/routes/components/layout/article-content-wrapper/+page.md
  docs/src/routes/components/layout/article/+page.md
  docs/src/routes/components/layout/div-content-wrapper/+page.md
  docs/src/routes/components/layout/div/+page.md
  docs/src/routes/components/layout/layout-authentication/+page.md
  docs/src/routes/components/layout/layout-form/+page.md
  docs/src/routes/components/layout/layout-set/+page.md
  docs/src/routes/components/layout/main-content-wrapper/+page.md
  docs/src/routes/components/layout/main/+page.md
  docs/src/routes/components/layout/section-content-wrapper/+page.md
  docs/src/routes/components/layout/section/+page.md
  docs/src/routes/components/layout/typography/body-text-set/+page.md
  docs/src/routes/components/layout/typography/heading-base-set/+page.md
  docs/src/routes/examples/pages/login/+page@.svelte
  docs/src/routes/utility/+page.svelte
  docs/src/routes/utility/background-color-offset/+page.md
  docs/src/routes/utility/centered/+page.md
  docs/src/routes/utility/column-2/+page.md
  docs/src/routes/utility/column-3/+page.md
  docs/src/routes/utility/column-4/+page.md
  docs/src/routes/utility/columns/+page.md
  docs/src/routes/utility/container/+page.md
  docs/src/routes/utility/fifty-fifty/+page.md
  docs/src/routes/utility/focus-only/+page.md
  docs/src/routes/utility/hidden/+page.md
  docs/src/routes/utility/horizontal-scroll/+page.md
  docs/src/routes/utility/horizontal/+page.md
  docs/src/routes/utility/one-third-two-thirds/+page.md
  docs/src/routes/utility/two-thirds-one-third/+page.md
  docs/src/routes/utility/visually-hidden/+page.md
  docs/src/scss/main.scss
  manon/components/description-list.scss
  manon/components/div.scss
  manon/components/horizontal-center.scss
  manon/components/horizontal-scroll.scss
  manon/components/horizontal-view.scss
  manon/components/layout-authentication.scss
  manon/components/layout-form.scss
  manon/components/main-content-wrapper.scss
  manon/components/main.scss
  manon/utility/column-2.scss
  manon/utility/column-3.scss
  manon/utility/columns.scss
  manon/utility/container.scss
  manon/utility/horizontal.scss
  manon/variables/_columns.scss
  manon/variables/_container.scss
  manon/variables/_description-list.scss
  manon/variables/_index.scss
  manon/variables/_layout-authentication.scss
  manon/variables/_layout-form.scss
  manon/variables/_main-content-wrapper.scss
  manon/variables/_main.scss
  themes/icore-open/_index.scss
Labels: breaking change, v18

#1023 fix: Example pages header position
  docs/src/routes/examples/pages/basic/+page@.svelte
Labels: v18

#1029 refactor: move examples to snippets
  docs/src/routes/components/components/breadcrumb/+page.md
  docs/src/routes/components/components/header-navigation/+page.md
  docs/src/routes/components/components/navigation/+page.md
  docs/src/routes/components/components/notifications/notifications-page-confirmation/+page.md
  docs/src/routes/components/components/notifications/notifications-page-error/+page.md
  docs/src/routes/components/components/notifications/notifications-page-explanation/+page.md
  docs/src/routes/components/components/notifications/notifications-page-system/+page.md
  docs/src/routes/components/components/notifications/notifications-page-warning/+page.md
  docs/src/routes/components/components/sidemenu/+page.md
  docs/src/routes/components/components/sidemenu/in-page-collapsible/+page.md
  docs/src/routes/components/components/sidemenu/in-page/+page.md
  docs/src/routes/components/components/sidemenu/next-to-page-collapsible/+page.md
  docs/src/routes/components/components/sidemenu/next-to-page/+page.md
  docs/src/routes/components/components/skip-to-content/+page.md
  docs/src/routes/examples/footer-navigation-link-unvisited/+page.svelte
  docs/src/routes/examples/skip-to-content/+page.svelte
  docs/src/routes/snippets/breadcrumb-bar/+page.svelte
  docs/src/routes/snippets/footer-link-unvisited/+page.svelte
  docs/src/routes/snippets/footer-link-visited/+page.svelte
  docs/src/routes/snippets/footer-navigation-link-unvisited/+page.svelte
  docs/src/routes/snippets/footer-navigation-link-visited/+page.svelte
  docs/src/routes/snippets/header-navigation-link-unvisited/+page.svelte
  docs/src/routes/snippets/header-navigation-link-visited/+page.svelte
  docs/src/routes/snippets/header-navigation-with-content-wrapper/+page.svelte
  docs/src/routes/snippets/header-navigation-with-form-button/+page.svelte
  docs/src/routes/snippets/header-navigation-with-logo/+page.svelte
  docs/src/routes/snippets/header-navigation-with-multiple-menus/+page.svelte
  docs/src/routes/snippets/header-navigation-with-search/+page.svelte
  docs/src/routes/snippets/header-navigation/+page.svelte
  docs/src/routes/snippets/heading-link-external-unvisited/+page.svelte
  docs/src/routes/snippets/heading-link-external-visited/+page.svelte
  docs/src/routes/snippets/heading-link-icon-unvisited/+page.svelte
  docs/src/routes/snippets/heading-link-icon-visited/+page.svelte
  docs/src/routes/snippets/heading-link-unvisited/+page.svelte
  docs/src/routes/snippets/heading-link-visited/+page.svelte
  docs/src/routes/snippets/link-external-unvisited/+page.svelte
  docs/src/routes/snippets/link-external-visited/+page.svelte
  docs/src/routes/snippets/link-icon-unvisited/+page.svelte
  docs/src/routes/snippets/link-icon-visited/+page.svelte
  docs/src/routes/snippets/link-pseudocontent-icon-unvisited/+page.svelte
  docs/src/routes/snippets/link-pseudocontent-icon-visited/+page.svelte
  docs/src/routes/snippets/link-unvisited/+page.svelte
  docs/src/routes/snippets/link-visited/+page.svelte
  docs/src/routes/snippets/navigation-link-unvisited/+page.svelte
  docs/src/routes/snippets/navigation-link-visited/+page.svelte
  docs/src/routes/snippets/navigation-with-horizontal/+page.svelte
  docs/src/routes/snippets/navigation-with-list-of-links/+page.svelte
  docs/src/routes/snippets/sidemenu-in-page-collapsible/+page.svelte
  docs/src/routes/snippets/sidemenu-in-page-expandable/+page.svelte
  docs/src/routes/snippets/sidemenu-in-page/+page.svelte
  docs/src/routes/snippets/sidemenu-next-to-page-collapsible/+page.svelte
  docs/src/routes/snippets/sidemenu-next-to-page-expandable/+page.svelte
  docs/src/routes/snippets/sidemenu-next-to-page/+page.svelte
  docs/src/routes/snippets/skip-to-content/+page.svelte
Labels: v18

#1035 feat: Accordion iCore Open theme styling
  docs/src/routes/library/components/accordion/+page.md
  manon/components/accordion.scss
  manon/variables/_accordion.scss
  themes/icore-open/_index.scss
Labels: v18

#1036 chore: update some texts
  README.en.md
  README.md
  docs/src/lib/SiteNavLinks.svelte
  docs/src/routes/+page.svelte
Labels: v18

#1039 feat: functionality to manually deploy specific version of the docs
  .github/workflows/github-pages-version.yml
Labels: v17

#1060 fix: div default behaviour
  manon/components/article-section.scss
  manon/components/article.scss
  manon/components/div.scss
  manon/components/footer.scss
  manon/components/hero.scss
  manon/components/section.scss
  manon/variables/_div.scss
Labels: v18

#1054 feat: add documentation version links
  docs/src/routes/+page.svelte
Labels: v18

#1064 fix: issue with `<a>` tag in navigation component documentation
  docs/src/routes/library/components/navigation/+page.md
Labels: v18

#1061 refactor: update examples
  docs/src/routes/getting-started/tutorial/+page.md
  examples/django/README.md
  examples/django/django-project/package-lock.json
  examples/django/django-project/package.json
  examples/sass-cli/README.md
  examples/sass-cli/css/main.css
  examples/sass-cli/css/main.css.map
  examples/sass-cli/index.html
  examples/sass-cli/main.scss
  examples/sass-cli/package.json
  examples/tutorial/README.md
  examples/tutorial/css/main.css
  examples/tutorial/css/main.css.map
  examples/tutorial/main.scss
  examples/tutorial/package-lock.json
  examples/tutorial/package.json
  examples/vite/README.md
  examples/vite/index.html
  examples/vite/main.scss
  pnpm-lock.yaml
Labels: v18

#1067 Fix pagination alignment
  manon/components/pagination.scss
  manon/variables/_pagination.scss
Labels: v18

#1016 fix: remove required form wrapper from radio inputs (#358)
  manon/radio.scss
Labels: v17

#1073 Fix article styling
  manon/components/article.scss
  manon/components/section.scss
Labels: v18

#1040 fix: table components navigation and introductions
  docs/src/routes/library/components/table/table-base/+page.md
  docs/src/routes/library/components/table/table-checkbox/+page.md
  docs/src/routes/library/components/table/table-checkbox/+page.svelte
  docs/src/routes/library/components/table/table-multiple-columns/+page.md
  docs/src/routes/library/components/table/table-scope/+page.md
  docs/src/routes/library/components/table/table-sortable/+page.md
  docs/src/routes/library/components/table/table-sortable/+page.svelte
  docs/src/scss/main.scss
  manon/components/form-inline.scss
  manon/components/table-checkbox.scss
  manon/components/table.scss
  manon/variables/_form-inline.scss
  manon/variables/_index.scss
  manon/variables/_table-checkbox.scss
  manon/variables/_table.scss
  themes/icore-open/_index.scss
Labels: v18

#1077 fix: nota bene docs
  docs/src/routes/library/typography/nota-bene/+page.md
Labels: v18

#1079 fix: update tutorial
  docs/src/routes/+page.svelte
  docs/src/routes/getting-started/tutorial/+page.md
Labels: v18
